var CONFIG = {};

CONFIG.BLOG_TITLE = 'CS#@!^ Blog';
CONFIG.NAV_TITLE = 'Chunmun CS#@!^';

CONFIG.SHOW_SIDEBAR = true;
CONFIG.NUM_POSTS_IN_SIDEBAR = 5;
CONFIG.NUM_POSTS_PER_PAGE = 4;
CONFIG.ENABLE_ANIMATIONS = true;

CONFIG.USE_DISQUS = true;
CONFIG.DISQUS_SHORT_NAME = 'chunmun3216blog';
CONFIG.SITE_DOMAIN = 'chunmun.github.io/CS3216/#';
